INSERT INTO CursoEG VALUES (CURSO_ID_CURSO_SEQ_1.NEXTVAL, 'Odontologia', 'Pedro');
INSERT INTO CursoEG VALUES (CURSO_ID_CURSO_SEQ_1.NEXTVAL, 'Ciencia da Computacao', 'Fernando');
INSERT INTO CursoEG VALUES (CURSO_ID_CURSO_SEQ_1.NEXTVAL, 'Medicina', 'Rafael');


INSERT INTO ProfessoresEG VALUES (PROFESSOR_ID_PROFESSOR.NEXTVAL, 'Howard', 5, 2);
INSERT INTO ProfessoresEG VALUES (PROFESSOR_ID_PROFESSOR.NEXTVAL, 'Leticia', 3, 3);
INSERT INTO ProfessoresEG VALUES (PROFESSOR_ID_PROFESSOR.NEXTVAL, 'Joao', 4, 1);


INSERT INTO AlunosEG VALUES (ALUNOS_MATRICULA_SEQ.NEXTVAL, 'Maria', 12334567855, 3);
INSERT INTO AlunosEG VALUES (ALUNOS_MATRICULA_SEQ.NEXTVAL, 'Gabriel', 23421127855, 2);
INSERT INTO AlunosEG VALUES (ALUNOS_MATRICULA_SEQ.NEXTVAL, 'Marcos', 26354718294, 1);
INSERT INTO AlunosEG VALUES (ALUNOS_MATRICULA_SEQ.NEXTVAL, 'Carlos', 99988823465, 2);